version: "3"

services:
    web:
        build:
            context: .
            dockerfile: ./compose/web/Dockerfile
        depends_on:
            - db
        ports:
        - 5000:5000
        networks:
            - default
        volumes:
            - ./:/webapp/
            - ./migrations:/webapp/migrations
        env_file:
            - dev.env
        restart: always
        entrypoint: sh entrypoint.sh
    db:
        build: 
            context: .
            dockerfile: ./compose/postgres/Dockerfile
        networks:
            - default
        ports:
            - 5405:5432
        env_file:
            - dev.env
        restart: always
        volumes:
            - ./postgres-data:/var/lib/postgresql/data