"""empty message

Revision ID: 345ecd257f35
Revises: 
Create Date: 2020-11-07 07:35:40.289507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345ecd257f35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
